name: Biome lint and format

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "24 14 * * 1"
  workflow_dispatch: 


jobs:
  biome:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: true
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "2.2.3"
      - name: Run Biome
        run: biome ci .