name: typecheck and test

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "24 14 * * 1"
  workflow_dispatch: 


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: false
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22.x
          cache: pnpm
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Restore tsbuildinfo
        uses: actions/cache/restore@v4
        with:
          path: node_modules/.cache/*.tsbuildinfo
          key: ${{ runner.os }}-tsbuild-${{ hashFiles('**/tsconfig*.json') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-tsbuild-${{ hashFiles('**/tsconfig*.json') }}-
      - name: Run test
        run: pnpm run test
      - name: Save tsbuildinfo
        if: success()
        uses: actions/cache/save@v4
        with:
          path: node_modules/.cache/*.tsbuildinfo
          key: ${{ runner.os }}-tsbuild-${{ hashFiles('**/tsconfig*.json') }}-${{ github.run_id }}
