name: typecheck and test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          submodules: true
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 22.x
          cache: pnpm
      - name: Cache TypeScript incremental builds
        uses: actions/cache@v4
        with:
          path: |
            **/*.tsbuildinfo
            node_modules/.cache
          key: ${{ runner.os }}-typescript-${{ hashFiles('**/tsconfig*.json') }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-typescript-${{ hashFiles('**/tsconfig*.json') }}-
            ${{ runner.os }}-typescript-
      - name: Cache Vitest
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.vitest
            coverage
          key: ${{ runner.os }}-vitest-${{ hashFiles('**/vitest.config.*', '**/package.json') }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-vitest-${{ hashFiles('**/vitest.config.*', '**/package.json') }}-
            ${{ runner.os }}-vitest-
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run test
        run: pnpm run test
